In [1]:
import torch
import numpy as np

In [2]:
random_array = np.random.randn(3,5)

In [3]:
random_array

array([[-0.48077509,  0.50296354,  0.39637246, -2.05721809,  0.42379393],
       [-1.69106577,  0.76618296,  0.81974676, -0.06383293, -0.04350726],
       [-0.65040646, -0.51088921,  1.00927442,  1.17428965, -1.48907968]])

In [4]:
type(random_array)

numpy.ndarray

In [5]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

In [8]:
random_matrix = torch.rand(size = (3,5))

In [9]:
random_matrix

tensor([[0.6132, 0.1788, 0.8406, 0.7018, 0.5505],
        [0.3293, 0.6630, 0.5626, 0.1396, 0.7821],
        [0.2491, 0.1585, 0.8294, 0.8772, 0.8503]])

In [10]:
random_matrix.ndim

2

In [11]:
random_matrix.shape

torch.Size([3, 5])

In [12]:
random_matrix.dtype

torch.float32

In [13]:
random_image_tensor = torch.rand(size = (224,224,3))

In [14]:
random_image_tensor

tensor([[[5.6303e-01, 6.9708e-01, 4.4167e-01],
         [4.6361e-01, 5.6060e-01, 8.7506e-01],
         [6.7116e-01, 6.4111e-02, 3.9512e-01],
         ...,
         [7.5355e-01, 2.1376e-01, 4.9620e-01],
         [8.8811e-01, 9.0386e-01, 1.1496e-01],
         [1.3537e-01, 1.4557e-01, 8.2391e-02]],

        [[5.8644e-01, 1.4569e-01, 7.6022e-01],
         [8.9187e-01, 8.8480e-01, 5.0868e-01],
         [7.2978e-01, 7.4075e-01, 6.4888e-02],
         ...,
         [8.5287e-01, 2.7380e-01, 9.7932e-01],
         [8.9821e-02, 6.1963e-01, 5.0773e-01],
         [9.3866e-01, 6.7568e-01, 6.7692e-01]],

        [[5.2310e-03, 4.0495e-01, 7.9292e-01],
         [3.9245e-02, 3.8413e-01, 8.8117e-01],
         [2.3139e-04, 8.2130e-01, 3.9585e-01],
         ...,
         [8.9466e-01, 8.1391e-01, 4.4022e-02],
         [4.3670e-01, 8.5853e-01, 9.5705e-01],
         [4.7085e-01, 8.7572e-01, 4.6096e-01]],

        ...,

        [[6.1603e-01, 3.9162e-02, 5.5029e-01],
         [9.6776e-01, 4.9000e-01, 9.8122e-01]

In [15]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [16]:
random_image_tensor.ndim

3

In [17]:
zeros = torch.zeros(size = (3,3,3,3))

In [18]:
zeros

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

In [19]:
zeros.shape

torch.Size([3, 3, 3, 3])

In [20]:
ones = torch.ones(size = (2,2))

In [21]:
ones

tensor([[1., 1.],
        [1., 1.]])

In [22]:
vector_with_arange = torch.arange(start = 1, end = 10, step = 1)

In [23]:
vector_with_arange

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
similar_ones = torch.ones_like(vector_with_arange)

In [25]:
similar_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
x_tensor = torch.tensor([1,2,3])
x_tensor + 15

tensor([16, 17, 18])

In [27]:
x_tensor * 12

tensor([12, 24, 36])

In [28]:
x_tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [29]:
x_tensor = x_tensor + 10

In [30]:
x_tensor

tensor([11, 12, 13])

In [31]:
x_tensor.subtract(10)

tensor([1, 2, 3])

In [32]:
x_tensor = x_tensor.subtract(10)

In [33]:
x_tensor

tensor([1, 2, 3])

In [34]:
x_tensor.multiply(10)

tensor([10, 20, 30])

In [35]:
x_tensor.add(10)

tensor([11, 12, 13])

In [36]:
x_tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [37]:
x_tensor * x_tensor

tensor([1, 4, 9])

In [38]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [39]:
x_tensor / x_tensor

tensor([1., 1., 1.])

In [40]:
y_tensor = torch.tensor([1,2])

In [41]:
x_tensor + y_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0