In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

In [3]:
torch.backends.mps.is_available()

True

In [4]:
device = "mps" if torch.backends.mps.is_available() else "cpu"

In [5]:
device

'mps'

In [6]:
tensor = torch.tensor([1,2,3])

In [7]:
tensor

tensor([1, 2, 3])

In [8]:
tensor.device 

device(type='cpu')

In [9]:
# manual

In [10]:
tensor_on_gpu = tensor.to(device)

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

In [12]:
tensor.numpy()

array([1, 2, 3])

In [14]:
# this numpy function is not able to run on mps (gpu)

# tensor_on_gpu.numpy()

In [15]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [16]:
# context manager

In [17]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)

In [18]:
tensor2.device

device(type='mps', index=0)

In [19]:
layer.weight.device

device(type='mps', index=0)

In [20]:
tensor3 = torch.tensor([1,2,3])
tensor3.device

device(type='cpu')

In [21]:
# torch.set_default_device

In [22]:
device

'mps'

In [23]:
torch.set_default_device(device)

In [24]:
tensor4 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(20,30)

In [25]:
tensor4.device

device(type='mps', index=0)

In [26]:
layer2.weight.device

device(type='mps', index=0)