In [4]:
!pip install torch torchvision

  Using cached torch-2.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (29 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 43.2 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [torchvision] 1/2 [torchvision]


In [5]:
import torch
import numpy as np

In [6]:
# pytorch datatypes: tensors

In [7]:
torch.tensor(10)

tensor(10)

In [9]:
torch.tensor([10,20])

tensor([10, 20])

In [11]:
torch.tensor([[10,20], [10,20]])

tensor([[10, 20],
        [10, 20]])

In [12]:
scalar = torch.tensor(10)

In [14]:
type(scalar)

torch.Tensor

In [15]:
scalar + 5

tensor(15)

In [16]:
scalar - 10

tensor(0)

In [17]:
scalar / 2

tensor(5.)

In [18]:
scalar * 3

tensor(30)

In [19]:
scalar.dim()

0

In [20]:
scalar.shape

torch.Size([])

In [22]:
scalar.item()

10

In [23]:
type(scalar.item())

int

In [24]:
numpy_int = np.int32(10)

In [25]:
numpy_int + 10

np.int32(20)

In [26]:
numpy_int - 10

np.int32(0)

In [27]:
numpy_int * 3

np.int32(30)

In [28]:
numpy_int / 2

np.float64(5.0)

In [29]:
scalar_from_np = torch.tensor(numpy_int)

In [31]:
scalar_from_np.dtype

torch.int32

In [32]:
scalar.dtype

torch.int64

In [33]:
new_scalar = torch.tensor(10, dtype = torch.int16)

In [34]:
new_scalar

tensor(10, dtype=torch.int16)

In [35]:
tensor_float = torch.tensor(3.14)

In [36]:
tensor_float.dtype

torch.float32

In [37]:
tensor_float64 = torch.tensor(3.14, dtype = torch.float64)

In [38]:
tensor_float64

tensor(3.1400, dtype=torch.float64)

In [39]:
# vectors

In [40]:
vector = torch.tensor([10,20])

In [41]:
vector.dim()

1

In [43]:
vector.ndim

1

In [44]:
vector.shape

torch.Size([2])

In [45]:
vector = torch.tensor([1,2,3])

In [46]:
vector.dim()

1

In [47]:
vector.shape

torch.Size([3])

In [48]:
# count # of [ => dimension
# count elements => shape

In [49]:
matrix = torch.tensor([[1,2],[3,4]])

In [50]:
matrix

tensor([[1, 2],
        [3, 4]])

In [51]:
matrix.dim()

2

In [52]:
matrix.shape

torch.Size([2, 2])

In [57]:
tensor_example = torch.tensor([[[1,2,3],[3,4,5],[6,7,8]]])

In [58]:
tensor_example.dim()

3

In [59]:
tensor_example.shape

torch.Size([1, 3, 3])

In [60]:
float_16_tensor = torch.tensor([10,20,30], dtype = torch.float16)

In [61]:
float_16_tensor

tensor([10., 20., 30.], dtype=torch.float16)