In [2]:
import torch
import numpy as np

In [3]:
tensor1 = torch.arange(0,50,5)

In [4]:
tensor1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
tensor1.min()

tensor(0)

In [6]:
tensor1.max()

tensor(45)

In [7]:
tensor1.sum()

tensor(225)

In [8]:
tensor1.median()

tensor(20)

In [9]:
# tensor1.mean() => leads to an error

tensor1 = tensor1.type(torch.float32)

In [10]:
tensor1.mean()

tensor(22.5000)

In [11]:
# argmax, argmin
tensor1.max()

tensor(45.)

In [12]:
tensor1.argmax()

tensor(9)

In [13]:
tensor1[9]

tensor(45.)

In [14]:
matrix = torch.tensor([[1,2,3], [4,5,6]])

In [15]:
matrix.shape

torch.Size([2, 3])

In [16]:
matrix.ndim

2

In [17]:
matrix[0]

tensor([1, 2, 3])

In [18]:
matrix[0][0]

tensor(1)

In [19]:
matrix[0][0].item()

1

In [20]:
# manipulating tensors: reshaping, stacking, squeezing, unsqueezing

In [21]:
x = torch.arange(1,10, 1)

In [22]:
x.shape

torch.Size([9])

In [23]:
x.ndim

1

In [24]:
x_reshaped = x.reshape(1,9)

In [25]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
x_reshaped.shape

torch.Size([1, 9])

In [27]:
x_reshaped.ndim

2

In [28]:
y = torch.randn(224,224,3)

In [30]:
y.shape

torch.Size([224, 224, 3])

In [31]:
x_reshaped = x.reshape(3,3)

In [32]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
# leads us to an error
# x_reshaped = x.reshape(2,4)

In [35]:
x_reshaped = x.reshape(9,1)

In [36]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [37]:
# view

In [38]:
x_reshaped[0] = 20

In [39]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [42]:
x.is_contiguous()

True

In [43]:
y = x.t()

In [44]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [46]:
y.is_contiguous()

False

In [47]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [48]:
# this code snippet will leads us to an error because view function works exact the same with reshape func but the only difference between
# these two funcs is that view function only works with contiguous tensors. 

# y.view(1,6)

In [ ]:
y.