In [2]:
import torch
import numpy as np

In [3]:
tensor1 = torch.arange(0,50,5)

In [4]:
tensor1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
tensor1.min()

tensor(0)

In [6]:
tensor1.max()

tensor(45)

In [7]:
tensor1.sum()

tensor(225)

In [8]:
tensor1.median()

tensor(20)

In [9]:
# tensor1.mean() => leads to an error

tensor1 = tensor1.type(torch.float32)

In [10]:
tensor1.mean()

tensor(22.5000)

In [11]:
# argmax, argmin
tensor1.max()

tensor(45.)

In [12]:
tensor1.argmax()

tensor(9)

In [13]:
tensor1[9]

tensor(45.)

In [14]:
matrix = torch.tensor([[1,2,3], [4,5,6]])

In [15]:
matrix.shape

torch.Size([2, 3])

In [16]:
matrix.ndim

2

In [17]:
matrix[0]

tensor([1, 2, 3])

In [18]:
matrix[0][0]

tensor(1)

In [19]:
matrix[0][0].item()

1

In [20]:
# manipulating tensors: reshaping, stacking, squeezing, unsqueezing

In [21]:
x = torch.arange(1,10, 1)

In [22]:
x.shape

torch.Size([9])

In [23]:
x.ndim

1

In [24]:
x_reshaped = x.reshape(1,9)

In [25]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
x_reshaped.shape

torch.Size([1, 9])

In [27]:
x_reshaped.ndim

2

In [28]:
y = torch.randn(224,224,3)

In [30]:
y.shape

torch.Size([224, 224, 3])

In [31]:
x_reshaped = x.reshape(3,3)

In [32]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
# leads us to an error
# x_reshaped = x.reshape(2,4)

In [35]:
x_reshaped = x.reshape(9,1)

In [36]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [37]:
# view

In [38]:
x_reshaped[0] = 20

In [39]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [42]:
x.is_contiguous()

True

In [43]:
y = x.t()

In [44]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [46]:
y.is_contiguous()

False

In [47]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [48]:
# this code snippet will leads us to an error because view function works exact the same with reshape func but the only difference between
# these two funcs is that view function only works with contiguous tensors. 

# y.view(1,6)

In [49]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [50]:
# stacking

In [51]:
x 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [53]:
torch.stack([x,x,x,x], dim = 0)


tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [54]:
torch.stack([x,x,x,x], dim = 1)


tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [55]:
# squeeze and unsqueeze

In [56]:
x.shape

torch.Size([2, 3])

In [57]:
x.ndim

2

In [58]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [59]:
x = torch.tensor([[1,2,3]])

In [60]:
x.shape

torch.Size([1, 3])

In [61]:
x.ndim

2

In [62]:
x.squeeze()

tensor([1, 2, 3])

In [63]:
# the squeeze function only removes dimensions of size 1. if no such dimensions exist, the tensor remains unchanged.

In [65]:
x.squeeze().ndim

1

In [66]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [68]:
x.unsqueeze(dim = 0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [69]:
y = x.unsqueeze(dim = 0)

In [70]:
y.ndim

3

In [71]:
x.ndim

2

In [72]:
y.shape

torch.Size([1, 2, 3])

In [73]:
z = y.unsqueeze(dim = 0)

In [74]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [75]:
z.ndim

4

In [76]:
z.shape

torch.Size([1, 1, 2, 3])

In [77]:
t = z.squeeze()

In [78]:
t.ndim

2

In [79]:
t.shape

torch.Size([2, 3])

In [80]:
t.unsqueeze(dim = 1)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [81]:
# permute

In [82]:
x = torch.rand(size = (224,224,3))

In [83]:
x.shape

torch.Size([224, 224, 3])

In [84]:
x_permuted = x.permute(2,0,1)

In [85]:
x_permuted.shape

torch.Size([3, 224, 224])

In [86]:
# indexing and slicing

In [87]:
a = torch.arange(1,10,1)

In [88]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a = a.reshape(1,3,3)

In [90]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [91]:
a[0][0][0]

tensor(1)

In [92]:
a[:,0,0]

tensor([1])

In [93]:
a[:,1,0]

tensor([4])

In [94]:
a[:,:,0]

tensor([[1, 4, 7]])

In [95]:
a[:,0,:]

tensor([[1, 2, 3]])

In [97]:
# random seed

In [103]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])