In [2]:
import torch
import numpy as np

In [3]:
tensor = torch.tensor([1,2,3])

In [4]:
tensor * tensor

tensor([1, 4, 9])

In [5]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [6]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [7]:
# real matrix multiplication
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [8]:
torch.matmul(matrix, matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
tensor1 = torch.tensor([
    [1,2],
    [2,3],
    [4,5]
])
tensor2 = torch.tensor([
    [6,7],
    [8,9],
    [10,11]
])

In [10]:
tensor1.shape

torch.Size([3, 2])

In [11]:
tensor2.shape

torch.Size([3, 2])

In [12]:
# tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [13]:
# transpose 
tensor2.T

tensor([[ 6,  8, 10],
        [ 7,  9, 11]])

In [14]:
tensor2.T.shape

torch.Size([2, 3])

In [16]:
tensor1 @ tensor2.T

tensor([[20, 26, 32],
        [33, 43, 53],
        [59, 77, 95]])

In [17]:
A = torch.tensor([[1,2,3]])

In [18]:
A.shape

torch.Size([1, 3])

In [19]:
A.ndim

2

In [20]:
B = torch.tensor([[1],[2], [3]])

In [21]:
B.shape

torch.Size([3, 1])

In [22]:
B.ndim

2

In [24]:
result = A @ B

In [25]:
result.shape

torch.Size([1, 1])

In [26]:
result.ndim

2